POST http://localhost:9090/api/v1/fcfs
Content-Type: application/json

{
  "jobs": [
    {
      "process_id": 1,
      "arrival_time": 1,
      "cpu_time_1": 2,
      "io_time": 3,
      "cpu_time_2": 4
    },
    {
      "process_id": 2,
      "arrival_time": 12,
      "cpu_time_1": 3,
      "io_time": 4,
      "cpu_time_2": 1
    },
    {
      "process_id": 3,
      "arrival_time": 5,
      "cpu_time_1": 4,
      "io_time": 5,
      "cpu_time_2": 3
    },
    {
      "process_id": 4,
      "arrival_time": 13,
      "cpu_time_1": 4,
      "io_time": 5,
      "cpu_time_2": 15
    },
    {
      "process_id": 5,
      "arrival_time": 13,
      "cpu_time_1": 5,
      "io_time": 6,
      "cpu_time_2": 7
    }
  ]
}

###
